feature_tracker:
  min_keypoint_distance: 20.0
  max_keypoint_detection: 150
  max_init_frames: 60
  max_frames: 150
  predict_keypoints: true

initializer:
  keyframe_gap: 5
  min_matches: 50
  min_parallax: 10.0
  min_triangulation: 20
  min_points: 30

sliding_window_size: 8

solver:
  iteration_limit: 10
  time_limit: 1.0e6
